# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "hello-world-rs"
version = "0.1.1"
authors = [ "Vallabh Kansagara <vrkansagara@gmail.com>" ]
edition = "2021"
license-file = "LICENSE"
description = "Hello world in Rust language"

[dependencies]