name: Security audit

on:
  schedule:
    - cron: '* * * * *'
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master" ]



jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@issue-104
        with:
          token: ${{ secrets.GITHUB_TOKEN }}