name: Build and Test Rust Code

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release
    - name: Build release
      run: RUSTFLAGS="-C target-cpu=native" cargo build --release
    - name: Run tests
      run: cargo test --verbose
