name: Build and Test Rust Code

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --profile=dev --verbose
    - name: Build release ( Staging )
      run: cargo build --profile=staging --verbose
   - name: Build release
      run: cargo build --profile=release --verbose
    - name: Build release using native cpu
      run: RUSTFLAGS="-C target-cpu=native" cargo build --profile=release --verbose
    - name: Run tests
      run: cargo test --profile=test --verbose
